version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: allan_quant_root

  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "33060:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: allan_quant_root
  #     MYSQL_DATABASE: quant
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: allan_quant

  jupyterlab:
    image: allanwlz/ezqt-jupyter:latest
    container_name: jupyterlab
    volumes:
      - ../:/home/jovyan/lab
    ports:
      - "8081:8081"
    environment:
      JUPYTER_ENABLE_LAB: 'yes'

  metabase:
    image: metabase/metabase:v0.50.23
    container_name: metabase
    ports:
      - "3001:3000"

volumes:
  mongodb_data:
  mysql_data:
