version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: allan_quant_root

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: allan_quant_root
      MYSQL_DATABASE: quant
      MYSQL_USER: user
      MYSQL_PASSWORD: allan_quant

  jupyterlab:
    build: ./jupyterlab
    container_name: jupyterlab
    volumes:
      - ../jupyterlab:/home/jovyan/data
    ports:
      - "8081:8081"
    environment:
      JUPYTER_ENABLE_LAB: 'yes'

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
  mysql_data:
